### ISSUE TITLE
@DisableInstallInCheck for generated modules ( Hilt )

### ISSUE THREAD

**Issue by 4face-studi0** [square/AssistedInject#153] opened 2020-09-13 13:59 UTC
It might be nice to have optionally generated modules annotated with `@DisableInstallInCheck`

## Reason
As stated [here](https://dagger.dev/hilt/compiler-options#disable-install-in-check) compilation would fail unless we add the flag `-Adagger.hilt.disableModulesHaveInstallInCheck=true` or annotate the module.
Totally disabling the check by the flags could be dangerous, as stated in the doc
> By default, Hilt checks @Module classes for the @InstallIn annotation and raises an error if it is missing. This is because if someone accidentally forgets to put @InstallIn on a module, it could be very hard to debug that Hilt isn’t picking it up.

## How?
Not sure about the details of Annotations Processing and if it's possible to "understand" whether we're using Hilt or not, but as we have a `*-dagger2` artifact, it might worth to have an `*-hilt` one as well

**Comment by JakeWharton** [comment] 2020-09-13 16:46
Dupe of #150. Please try the snapshot and confirm it works for your case.

**Closed by JakeWharton** 2020-09-13 16:46 UTC

**Comment by 4face-studi0** [comment] 2020-09-14 06:32
@JakeWharton Seems to be working smootly
